channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - matplotlib
  - pandas
  - scikit-image
  - cartopy
  - jupyter_contrib_nbextensions
  - ipywidgets
  - tqdm
  - pip
  - pip:
    - PyGeodesy
